# Default values for atlas-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: arigaio/atlas-operator
  pullPolicy: IfNotPresent
  tag: ""

rbac:
  create: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  labels: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsNonRoot: true

containerSecurityContext:
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# By default, the operator will recreate devdb pods after migration
# Set this to true to keep the devdb pods around.
prewarmDevDB: true

devDB:
  prewarm: true
  images:
    postgres: "postgres:latest"
    sqlServer: "mcr.microsoft.com/mssql/server:2022-latest"
    mySql: "mysql:latest"
    mariaDb: "mariadb:latest"
    clickHouse: "clickhouse/clickhouse-server:latest"

# Enable this to allow custom project configuration
# Warning: This setting enables users to use the `external` and `sql` data sources
# which can be used to execute arbitrary commands and queries. Use with caution.
allowCustomConfig: false

# -- Additional environment variables to set
extraEnvs: []
# extraEnvs:
#   - name: FOO
#     valueFrom:
#       secretKeyRef:
#         key: FOO
#         name: secret-resource
#   - name: BAR
#     valueFrom:
#      configMapKeyRef:
#        key: BAR
#        name: config-map-resource

extraVolumes: []
# extraVolumes:
#   - name: extra-volume
#     secret:
#       secretName: extra-volume-secret

extraVolumeMounts: []
# extraVolumeMounts:
#   - name: extra-volume
#     mountPath: /extra-volume
#     readOnly: true

